### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Kichura** [FlorianMichael/ViaFabricPlus#1]
First one: Pressing F3 does not tell the user what client we are on and what server version it has been gotten *(Can be noticed in viafabric's F3 text),*

Second one: The GUI is not as clear to use than ViaFabric's, Now while it has a much more comfortable system of picking the version you need - For this one; there is no automatic mode for it, the values page doesn't actually indicate if options there are actually false or not when being colorblind *(for example)* and the user cannot figure out if you can close it out or have to restart the client without pressing ESC in practice,

Third one: Since this ultimately breaks viafabric itself entirely, The mod should disable it or indicate the user that it cannot be combined,

Fourth one *(forgotten to add this)*: If automatic mode did exist, Allow all added servers to be checked to see what versions they are on - On ViaFabric, It would display the ping result as expected but below it expose the server version using blue ping instead of green.

**Comment by FlorianMichael** [comment]
Thanks for the suggestions, once I'm done with all the porting I'll implement it all piece by piece

**Comment by FlorianMichael** [comment]
In the F3 menu debug values are displayed from now on, the GUI I have also reworked that it is now nicer and more understandable, an Auto Detect I will probably not add, because that does not work for many Minecraft versions and is also otherwise very unstable. The README is now also more clearly formulated and it is above indicated that this is incompatible with ViaFabric

**Comment by FlorianMichael** [comment]
Can this issue be closed then?

**Comment by Kichura** [comment]
Yes i can close it.

**Comment by Kas-tle** [comment]
Perhaps instead of auto detection allow the user to set a specific version for a given server list entry? This would still allow for quick server switching without having to worry about the mod trying to figure out what version to pick.
