### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by ENTJ07** [FlorianMichael/ViaFabricPlus#104]
### General Information

NoSuchFieldError: v1_20
<html>at com.viaversion.viaversion.protocol.ProtocolManagerImpl.registerProtocols(ProtocolManagerImpl.java:185)<br>at com.viaversion.viaversion.ViaManagerImpl.init(ViaManagerImpl.java:91)<br>at de.florianmichael.vialoadingbase.ViaLoadingBase.initPlatform(ViaLoadingBase.java:125)<br>at de.florianmichael.vialoadingbase.ViaLoadingBase.&lt;init&gt;(ViaLoadingBase.java:82)<br>at de.florianmichael.vialoadingbase.ViaLoadingBase$ViaLoadingBaseBuilder.build(ViaLoadingBase.java:255)<br>at de.florianmichael.viafabricplus.protocolhack.ProtocolHack.init(ProtocolHack.java:217)<br>at de.florianmichael.viafabricplus.ViaFabricPlus.init(ViaFabricPlus.java:74)<br>at net.minecraft.client.main.Main.handler$bjh000$viafabricplus$preLoad(Main.java:1032)<br>at net.minecraft.client.main.Main.main(Main.java:152)<br>at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)<br>at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)<br>at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)</html>

### Bug Description

Game fails to launch and crashes

### Steps to Reproduce

1. my mod list : fabric api 0.81.1 (1.19.4) viafabricplus 2.7.3
2. fabric loader 1.19.4

### Expected Behavior

The game should launch

**Comment by FlorianMichael** [comment]
What mods do you have installed?

**Comment by ENTJ07** [comment]
meteor client(1.19.4)+ client addons

**Comment by FlorianMichael** [comment]
Can you try to remove all of them (Only start ViaFabricPlus and FabricAPI)

**Comment by ENTJ07** [comment]
It works with out the mods. I think meteor has issue with this mod

**Comment by FlorianMichael** [comment]
which addon?

**Comment by ENTJ07** [comment]
https://github.com/bruh1273/Master-Meteor-Project

**Comment by Wide-Cat** [comment]
I'd recommend against using that mod pack, it's made quite haphazardly. Just download the addons/mods you want to use seperately.

**Comment by FlorianMichael** [comment]
Ik why it crashes, they just included ViaFabric lol xd

**Comment by Wide-Cat** [comment]
yeah
