### ISSUE TITLE
Cant Join Bedrock servers

### ISSUE THREAD

**Issue by Coop3rr** [FlorianMichael/ViaFabricPlus#105]
### General Information

when i select the version to bedrock, and join it stays on connecting to server.

### Bug Description

when joining the hive on the bedrock version, it fails to join

### Steps to Reproduce

1. joining the hive
2. stays on "connecting to server"

### Expected Behavior

i expected to join the server

**Comment by HowardZHY** [comment]
please send your latest.log in .minecraft/logs

**Comment by FlorianMichael** [comment]
on what ip are you joining?

**Comment by Coop3rr** [comment]
[20:36:37] [Server Connector #19/ERROR]: Caught previously unhandled exception :
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "java.lang.Exception.getMessage()" is null
	at net.minecraft.class_412$1.run(class_412.java:97) ~[client-intermediary.jar:?]

**Comment by Coop3rr** [comment]
play.hivemc.com

**Comment by FlorianMichael** [comment]
its the wrong IP, you have to join on: fr.hivebedrock.network:19132

**Comment by Coop3rr** [comment]
oh, sorry for waisting your time.

**Comment by Coop3rr** [comment]
so with this can i play with bedrock users who are playing on the hive?

**Comment by FlorianMichael** [comment]
it's in a very alpha stage, you can't really play atm

**Comment by Coop3rr** [comment]
okay, are there any other bedrock servers that work with other people?

**Comment by FlorianMichael** [comment]
No
