### ISSUE TITLE
I can't add my bedrock account

### ISSUE THREAD

**Issue by SubwaySurfers69** [FlorianMichael/ViaFabricPlus#109]
### General Information

![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/88637238/a01b70c5-ffb0-47f0-adab-5207ee0d1267)
Prism launcher btw

### Bug Description

when I try to add my bedrock account it just stays on this screen forever:
![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/88637238/ad72e23a-ff9e-4c9a-a81d-963dbd39210d)

### Steps to Reproduce

go to config, click "Click to set account for bedrock addition", copy the code, paste it into the browser, sign in to Microsoft, close the browser, and wait indefinitely

### Expected Behavior

I expect it to close that screen and let me play with a bedrock account

**Comment by SubwaySurfers69** [comment]
I'm trying it without all those mods in case that changes it

**Comment by SubwaySurfers69** [comment]
the same thing happens with only ViaFabricPlus and Fabric API.
also, I noticed when signing in it said I was signed into Minecraft for Nintendo Switch which I am not
![image](https://github.com/FlorianMichael/ViaFabricPlus/assets/88637238/94dbd423-1203-47ea-b317-de46e9f8d7fe)

**Comment by I-Got-You-Dead2** [comment]
That’s just how it works

**Comment by FlorianMichael** [comment]
Please send me your latest.log

**Comment by SubwaySurfers69** [comment]
sorry it took me so long I was outside
[latest.log](https://github.com/FlorianMichael/ViaFabricPlus/files/11583349/latest.log)

**Comment by RaphiMC** [comment]
@FlorianMichael I fixed the issue in 2.1.4-SNAPSHOT: https://github.com/RaphiMC/MinecraftAuth/commit/35de770af013dfa1b4d9ec75249c7de115feb1fc

**Comment by FlorianMichael** [comment]
@RaphiMC Thanks!
