### ISSUE TITLE
Hope to add multilingual support

### ISSUE THREAD

**Issue by luluxiaoyu** [FlorianMichael/ViaFabricPlus#14]
I hope that the language display of the mod settings page can be modified, but it seems that the json of the language file is not provided for direct modification like other mods

**Comment by FlorianMichael** [comment]
There is no Multi Language system at the moment, everything is in English only, there are no language files.

**Comment by FlorianMichael** [comment]
I have now coded and added the base for it, anyone who wants to do translations can do it now
