### ISSUE TITLE
[1.19.4->1.8.9]About player?

### ISSUE THREAD

**Issue by x-yingcan-x** [FlorianMichael/ViaFabricPlus#15]
#### What happended?
Successful Launch
Successfully entered the server (wdsj.net) and entered a mini-game (bed war)
The game started and didn't crash
When I want to bridge, the game crashed

[latest.log](https://github.com/FlorianMichael/ViaFabricPlus/files/11010470/latest.log)
My Launcher tells me it's about Player
I'm sorry to bother you, I'm not sure if this problem is caused by ViafabricPlus

**Comment by FlorianMichael** [comment]
This is not a ViaFabricPlus issue, "BetterSneak" is broken, try without it
