### ISSUE TITLE
Creative inventory is broken

### ISSUE THREAD

**Issue by gepron1x** [FlorianMichael/ViaFabricPlus#16]
Server version: 1.16.5
Client version: 1.19.3
Using the latest build
![изображение](https://user-images.githubusercontent.com/56407064/226199700-9b4b501b-78c3-4bc2-90e6-3b4872ab0635.png)

**Comment by FlorianMichael** [comment]
Please use the latest build of modrinth or curseforge, the bug is fixed long time ago
