### ISSUE TITLE
Sneaking in Multiplayer server does not move camera to correct position.

### ISSUE THREAD

**Issue by etianl** [FlorianMichael/ViaFabricPlus#25]
When pressing the sneakKey, the camera doesn't shift down as far as it should. When sneaking under a slab the camera is so far up it clips into the slab above your head prevent blocks from being able to be targeted. The server in question in 1.19.2, not sure if that matters

**Comment by etianl** [comment]
I should also note this does not occur in SinglePlayer, only multiplayer and I just noticed it in this here 1.19.2 server I'm on now

**Comment by FlorianMichael** [comment]
Will be fixed in the next release
