### ISSUE TITLE
Does not startup

### ISSUE THREAD

**Issue by Satanaelcode** [FlorianMichael/ViaFabricPlus#27]
`[12:49:59] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.12 [12:49:59] [main/INFO]: Loading 4 mods: 	- fabricloader 0.14.12 	- java 18 	- minecraft 1.19.3 	- viafabricplus 2.3.5 [12:50:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/eugam/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT [12:50:00] [main/INFO]: Compatibility level set to JAVA_17 [12:50:00] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker) [12:50:00] [main/WARN]: Error loading class: net/minecraft/class_1761$class_8128 (java.lang.ClassNotFoundException: net/minecraft/class_1761$class_8128) Mar 23, 2023 12:50:00 PM org.polymc.EntryPoint listen SEVERE: Exception caught from launcher. java.lang.reflect.InvocationTargetException 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) 	at java.base/java.lang.reflect.Method.invoke(Method.java:577) 	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) 	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) 	at org.polymc.EntryPoint.listen(EntryPoint.java:144) 	at org.polymc.EntryPoint.main(EntryPoint.java:74) Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) 	... 6 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) 	... 14 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method preLoad(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in viafabricplus.mixins.json:base.MixinMain from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap viafabricplus-refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) 	... 17 more Mar 23, 2023 12:50:00 PM org.polymc.EntryPoint main INFO: Exiting with 1 `

**Comment by Satanaelcode** [comment]
Java

**Comment by FlorianMichael** [comment]
Please use pastebin

**Comment by FlorianMichael** [comment]
Please install Fabric-API

**Comment by Satanaelcode** [comment]
https://mclo.gs/ORYH1Ka

**Comment by Satanaelcode** [comment]
> Please use pastebin

I did

**Comment by FlorianMichael** [comment]
Please update to Minecraft 1.19.4

**Comment by Satanaelcode** [comment]
> Please update to Minecraft 1.19.4
is there a 1.19.3 version still on?

**Comment by FlorianMichael** [comment]
Its not supported anymore, the latest 1.19.3 is the Backport version on modrinth
