### ISSUE TITLE
Krypton breaks everything

### ISSUE THREAD

**Issue by rexlManu** [FlorianMichael/ViaFabricPlus#3]
Hey, I got the issue that I get kicked when joining a server;

## Response
![image](https://user-images.githubusercontent.com/32296940/222255686-d06438f3-caf5-4c25-b395-0b2e75263ca0.png)

## Setup

Version: viafabricplus-1.5.6.jar
Quilt: 0.18.1-beta.74
Client: 1.19.3
Selected version: 1.19-1.19.2
Server: 1.19.2 paper without plugins

**Comment by FlorianMichael** [comment]
Can you try it with Fabric only again?

**Comment by rexlManu** [comment]
Yea I investigated a bit and https://modrinth.com/mod/krypton is the problem.

**Comment by FlorianMichael** [comment]
Krypton should not be used, it does not only destroy ViaVersion, but also makes you Unlegit
