### ISSUE TITLE
Unable to interact with entities 1.7.10

### ISSUE THREAD

**Issue by Mycelious** [FlorianMichael/ViaFabricPlus#30]
When you try to interact with any entities (riding minecarts, trading with villagers) nothing happens.

**Comment by HowardZHY** [comment]
what other mods do you have?
also provide logs if you can

**Comment by FlorianMichael** [comment]
Please provide more details (installed mods, mc version, server)

**Comment by Mycelious** [comment]
Just Fabric API and ViaFabricPlus
1.19.4 client
vanilla 1.7.10 server

**Comment by FlorianMichael** [comment]
Can you try it using the ViaProxy? https://github.com/RaphiMC/ViaProxy

**Comment by Mycelious** [comment]
It works with ViaProxy.

**Comment by Mycelious** [comment]
Im able to ride minecarts using ViaProxy but not ViaFabricPlus

**Comment by FlorianMichael** [comment]
Fixed within the next version, thanks!

**Comment by FlorianMichael** [comment]
Fix now public in the latest release
