### ISSUE TITLE
Wrong sneaking height [1.8.9]

### ISSUE THREAD

**Issue by x-yingcan-x** [FlorianMichael/ViaFabricPlus#32]
ViaFabricPlus 2.3.7
mod menu 6.1.0 rc4
no other mods
1.19.4 -> 1.8.9
"Automatically change Settings" enabled
the hitbox while sneaking is right  but camera pos is wrong

**Comment by FlorianMichael** [comment]
Can you send a Photo, this should be fixed?

**Comment by x-yingcan-x** [comment]
Standing
![2023-03-25_20 07 27](https://user-images.githubusercontent.com/99530733/227716627-916222ec-35be-460a-b616-b20368146c24.png)
Sneaking ("Replace sneaking" disabled)
![2023-03-25_20 07 52](https://user-images.githubusercontent.com/99530733/227716656-c26b437f-0397-4be4-a82a-8dcbdb978c3c.png)
Sneaking ("Replace sneaking" enabled)
![2023-03-25_20 08 00](https://user-images.githubusercontent.com/99530733/227716667-0e012951-3613-44e9-b1fe-01e6ca6371ff.png)

**Comment by x-yingcan-x** [comment]
It works well in 2.3.5. Something broke it.

**Comment by x-yingcan-x** [comment]
I know but sneaking camera pos for 1.8.9 is wrong and the 1.7 one works well.
will be fixed? or need more information?

**Comment by FlorianMichael** [comment]
The 1.8.9 camera pos was wrong, it is fixed now

**Comment by FlorianMichael** [comment]
Can this be closed now?

**Comment by x-yingcan-x** [comment]
still not fixed

**Comment by FlorianMichael** [comment]
What you see now is correct, that's how it should be, it was wrong in the old version because I had broken the eye heights.

**Comment by x-yingcan-x** [comment]
It's wrong if you only want to sneaking instant but it's correct for 1.8.9 sneaking (both change sneaking speed and height)
Will this feature be added? (sneaking height tweak)

**Comment by FlorianMichael** [comment]
Found the issue, the sneaking height is now fixed within the next commit/release
