### ISSUE TITLE
Bedrock works incorectly

### ISSUE THREAD

**Issue by Fundi1330** [FlorianMichael/ViaFabricPlus#38]
When I try to join my server on Liteloader bds 1.19.72 (the protocol is the same as in 1.19.70), I successfully log in, sometimes I just spawn at the same height, and sometimes I fall and fly for a long time. Sometimes I appear in a strange place: 
![image](https://user-images.githubusercontent.com/88210377/227772320-363425ae-8937-4a21-af97-95bcf631859e.png)
. After some time, the server writes that I was kicked out of the game. At the same time, I don't poop. (yes, I know that Bedrock support is on the alpha version, I just reported that there is such a problem).

When I go to nether games or the hive on version 2.4.7(on 2.3.7 all working correctly), an error pops up, it also popped up for me when I went to my server:
![image](https://user-images.githubusercontent.com/88210377/227772122-e9ceded0-92fe-4a86-80ed-048541dd3d86.png)

**Comment by FlorianMichael** [comment]
As you said, the Bedrock is in alpha and therefore has a lot of bugs, I won't do anything about it for now because the bug will probably fix itself the more features are added.

**Comment by Walkersifolia** [comment]
> When I try to join my server on Liteloader bds 1.19.72 (the protocol is the same as in 1.19.70), I successfully log in, sometimes I just spawn at the same height, and sometimes I fall and fly for a long time. Sometimes I appear in a strange place: ![image](https://user-images.githubusercontent.com/88210377/227772320-363425ae-8937-4a21-af97-95bcf631859e.png) . After some time, the server writes that I was kicked out of the game. At the same time, I don't poop. (yes, I know that Bedrock support is on the alpha version, I just reported that there is such a problem).
> 
> When I go to nether games or the hive on version 2.4.7(on 2.3.7 all working correctly), an error pops up, it also popped up for me when I went to my server: ![image](https://user-images.githubusercontent.com/88210377/227772122-e9ceded0-92fe-4a86-80ed-048541dd3d86.png)

How to set the server ip in client to login a bedrock server? I even can't get in.
