### ISSUE TITLE
Implement ViaBackwards into this mod

### ISSUE THREAD

**Issue by Imzxhir** [FlorianMichael/ViaFabricPlus#4]
Description: I think ViaBackwards should be implemented into this mod because it could allow for when people are on 1.19.3 and they want to connect to 1.19.4 servers (when 1.19.4 comes out), it will be very easy to switch to it. Also, I was thinking that the mod could ported to 1.19.2 where ViaBackwards would really be helpful since there are many servers that support 1.19.3 but not 1.19.2 which is annoying since it forces people to upgrade.

**Comment by FlorianMichael** [comment]
It's already implemented

**Comment by FlorianMichael** [comment]
And to the backport: no, I will never support older Minecraft versions

**Comment by FlorianMichael** [comment]
Because it just doesn't make sense, there is no reason for me to use older Minecraft versions, the focus of ViaFabricPlus is mainly in the clientside fixes, and supporting them for multiple Minecraft versions is way too much work.

**Comment by FlorianMichael** [comment]
Let's see, but has no high priority with me
