### ISSUE TITLE
Change default port on Bedrock

### ISSUE THREAD

**Issue by RuiNtD** [FlorianMichael/ViaFabricPlus#40]
If possible, it would nice for Bedrock servers to use the default port of 19132 instead of 25565.

**Comment by I-Got-You-Dead2** [comment]
Just use <server ip>:19132

**Comment by RuiNtD** [comment]
> Just use <server ip>:19132

UX go brrrrrrrr

**Comment by FlorianMichael** [comment]
It's not that easy, if you just change the default port when Bedrock is selected it would break the pinging of the other servers, and since Bedrock is still in early alpha I find that a bit unnecessary, I will add that as soon as the Bedrock protocol is working properly.
