### ISSUE TITLE
Cannot use end portals in 1.19.4

### ISSUE THREAD

**Issue by AzyLooper** [FlorianMichael/ViaFabricPlus#41]
It is impossible to use end portals in 1.19.4. (This behaviour was only observed in Singleplayer, it doesn't affect Multiplayer)

How to reproduce:
-Find an end portal (literally any portal works)
-Try to use it

(Note that going inside the block using spectator mode and switching back to creative/survival still teleports you, it's just that the block itself has unwanted collisions, also I did test this bug with as little mods as possible, the only one being activated was Sodium since the game would refuse to launch without this mod, even with the ViaFabricPlus default settings)

Preview:
![2023-03-27_19 27 56](https://user-images.githubusercontent.com/36935069/228019979-df74e33c-4523-491f-a6fb-e1c59dd9891b.png)
![2023-03-27_19 27 57](https://user-images.githubusercontent.com/36935069/228019984-253308b4-1ad9-413c-98c9-dbc83ee59f0a.png)
![2023-03-27_19 28 11](https://user-images.githubusercontent.com/36935069/228019987-a4a2a5b2-7f8f-4b35-81e8-6bf996d55c98.png)
![2023-03-27_19 28 14](https://user-images.githubusercontent.com/36935069/228019997-002237f9-ff7a-482e-9f5f-63100c488baa.png)
![2023-03-27_19 30 50](https://user-images.githubusercontent.com/36935069/228020454-f67c223b-4342-4b44-b990-b70ec25df082.png)

**Comment by FlorianMichael** [comment]
Fixed, thank you!
