### ISSUE TITLE
Scoreboard issue on 1.8.x

### ISSUE THREAD

**Issue by BSMGPink** [FlorianMichael/ViaFabricPlus#44]
![image](https://user-images.githubusercontent.com/62712899/228593144-52d3f384-c506-49b5-963b-c390d3d18adf.png)

Errors within the scoreboard showing seemingly random [] characters

**Comment by FlorianMichael** [comment]
Known for a long time, not fixed yet, because all the fixes I've had so far just weren't good enough and often broke mods, so it's going to take a while until this is fixed properly.

**Comment by FlorianMichael** [comment]
fixed within https://github.com/FlorianMichael/ViaFabricPlus/commit/2dd154203c72f7a11563b9cb7cd77a9bb1a216dc
