### ISSUE TITLE
Certain faces not rendering properly with hoppers on 1.8.x

### ISSUE THREAD

**Issue by BSMGPink** [FlorianMichael/ViaFabricPlus#45]
1.19.4:
![image](https://user-images.githubusercontent.com/62712899/228594618-3b2470ad-2d46-4b9d-ad73-972a2c1568d4.png)
![image](https://user-images.githubusercontent.com/62712899/228594666-36cc13bd-fe63-432d-941f-a26443638bf9.png)

1.8.x:
![image](https://user-images.githubusercontent.com/62712899/228594738-0cdc267b-6282-4d79-b233-2a6a5fc6c2a6.png)
![image](https://user-images.githubusercontent.com/62712899/228594784-e37420b7-4962-4980-b11e-ae4728de31b2.png)

**Comment by FlorianMichael** [comment]
Can you send a list of all your mods ?

**Comment by FlorianMichael** [comment]
Fixed
