### ISSUE TITLE
[enhancement] Support Eaglercraft server

### ISSUE THREAD

**Issue by U5KUN** [FlorianMichael/ViaFabricPlus#46]

**Comment by FlorianMichael** [comment]
?

**Comment by MIOGMIOG** [comment]
Eaglercraft server is server for Minecraft clone.
ViaFabricPlus is implementation of other libraries that add support for other Minecraft version.
ViaFabricPlus is not a protocol translator, close this issue please.

**Comment by FlorianMichael** [comment]
I won't add support for Eaglercraft
