### ISSUE TITLE
Essential's setting menu button overlap with VFP's one in OptionsScreen

### ISSUE THREAD

**Issue by FurYzen** [FlorianMichael/ViaFabricPlus#5]
Description: when using Essential with VFP, the two mods tries to inject their respective option button in the same place, overlapping them. (note that the essential menu is prioritary, thus being opened)

Possible solutions: multiple fixes are possible, like: drawing our button elsewhere or just offsetting it downwards if essential is found,  but i think replacing the current button with a small rectangular one with the initials of the mod, somewhere like next to accessibility settings would be simpler and still a valid option, since it's unlikely than other mods will try to place theirs here.

I didnt make a pull request since i don't know how you would like to take the approach.

(sorry if some sentences are badly written, still learning)

**Comment by MIOGMIOG** [comment]
I know how to fix this.
1. Install latest dev build of ViaFabricPlus
2. Go to ViaFabricPlus settings and disable "Options button in game options" in "Bridge" settings category

**Comment by FlorianMichael** [comment]
Yeah, you can open the GUI Via ModMenu too, there is no requirement for the Custom button
