### ISSUE TITLE
Incompactible with Krypton

### ISSUE THREAD

**Issue by OstapOmega** [FlorianMichael/ViaFabricPlus#64]
### General Information

I have Mod menu, sodium, iris, ViaFabricPlus, Krypton, and many other optimizaton, and QoL mods installed. 

### Bug Description

Playing with version 2.2.0 1.19.3. Every time when i start the game it shows me error that it is incompactible with mod Krypton
https://modrinth.com/mod/krypton
![image](https://user-images.githubusercontent.com/67763024/233455552-0c9054d3-3fff-438c-8910-4a12dc325e5e.png)

### Steps to Reproduce

1. Hit play
2. See error

### Expected Behavior

The game should start normally

**Comment by FlorianMichael** [comment]
The 2.2.0 is old, it is no longer supported, please update to Minecraft 1.19.4 and ViaFabricPlus 2.6.3
