### ISSUE TITLE
Add the option to disable all Qol changes

### ISSUE THREAD

**Issue by pawa2401** [FlorianMichael/ViaFabricPlus#71]
Please add the option to disable all modifications that ViaFabricPlus makes aside from these which enable it to work. Some features from other mods interfere with some little changes that this mod makes, and I had to switch to regular ViaFabric for it to work, but aside from mod incompatibilities, a more advanced Qol settings would be nice.

**Comment by FlorianMichael** [comment]
No, for QoL changes that are very risky or that can break other mods, there are already settings, if there is a mod incompatibility then just report it, there is no reason to use ViaFabricPlus without the QoL changes, then you can just use normal ViaFabric or the ViaProxy.

**Comment by RaphiMC** [comment]
The whole point of ViaFabricPlus is to have clientside fixes / enhancements. If you disable everything its like having regular ViaFabric anyway

**Comment by allinkdev** [comment]
https://github.com/ViaVersion/ViaFabric
