### ISSUE TITLE
(Question) can i join bedrock realms using this?

### ISSUE THREAD

**Issue by ramide1** [FlorianMichael/ViaFabricPlus#72]
Minecraft bedrock is supported but i want to connect a minecraft friend's realm from java, the problem is minecraft realms has not ip address to share, it uses a invitation link or code.

**Comment by FlorianMichael** [comment]
It's not supported at the moment, but it will be in the future

**Comment by someElseIsHere** [comment]
Is it going to get supported anytime soon ?

**Comment by FlorianMichael** [comment]
Bedrock realms are now supported, see https://github.com/ViaVersion/ViaFabricPlus/issues/554
