### ISSUE TITLE
1.19.X multiplayer.disconnect.missing_public_key

### ISSUE THREAD

**Issue by Bluscream** [FlorianMichael/ViaFabricPlus#74]
### General Information

Mods:
  [✔] advancementinfo-1.19.4-fabric0.76.0-1.3.1
  [✔] animatica-0.5+1.19
  [✔] autofish-0.9.8-SNAPSHOT
  [✔] BetterF3-6.0.0-Fabric-1.19.4-pre3
  [✔] bobby-4.0.5
  [✔] borderlessmining-1.1.7+1.19.4
  [✔] c2me-fabric-mc1.19.4-0.2.0+alpha.10.51
  [✔] capes-1.5.2+1.19.3
  [✔] cem-0.7.3_S10_1.19.4
  [✔] chesttracker-1.1.21
  [✔] citresewn-1.1.3+1.19.4
  [✔] clientcommands-2.7.11
  [✔] cloth-config-10.0.96
  [✔] collective-1.19.4-6.54
  [✔] continuity-3.0.0-beta.2+1.19.3
  [✔] CreativeCore_FABRIC_v2.10.7_mc1.19.4
  [✔] Debugify-1.19.4+2.2
  [✔] dynamicfps-2.2.0
  [✔] eating-animation-1.9.3
  [✘] entity_model_features_fabric_1.19.4-0.2.8.jar (disabled)
  [✔] entity_texture_features_fabric_1.19.4-4.4.0
  [✔] entityculling-1.6.2-mc1.19.4
  [✔] entityinformation-1.19.4-3.0
  [✔] exordium-fabric-1.0.3-mc1.19.4
  [✔] fabric-api-0.79.0+1.19.4
  [✔] fabric-language-kotlin-1.9.3+kotlin.1.8.20
  [✔] fabricskyboxes-0.6.5+mc1.19.4
  [✔] fabrishot-1.9.2
  [✔] fallingleaves-1.15.0+1.19.4
  [✔] fancymenu_fabric_2.14.7_MC_1.19.4
  [✔] Fastload+1.18.2-1.20-3.3.8
  [✔] fastquit-2.1.0+1.19.3
  [✔] ferritecore-5.2.0
  [✔] ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric
  [✔] From-The-Fog-1.19-v1.8.1-Forge-Fabric
  [✔] fsb-interop-1.2.0+mc1.19.4-build.31
  [✔] ImmediatelyFast-1.1.12+1.19.4
  [✔] indium-1.0.15+mc1.19.4
  [✔] InventoryProfilesNext-fabric-1.19.4-1.9.6
  [✘] iris-mc1.19.4-1.6.1.jar (disabled)
  [✔] isxander-main-menu-credits-1.1.1
  [✔] jei-1.19.4-fabric-13.1.0.6
  [✔] jsmacros-1.8.4-beta-274c80c
  [✔] konkrete-1.6.0
  [✔] krypton-0.2.2
  [✔] lambdynlights-2.3.0+1.19.4
  [✔] languagereload-1.5.5+1.19.4
  [✔] lazydfu-0.1.3
  [✔] libIPN-fabric-1.19.4-2.0.6
  [✔] lithium-0.11.1
  [✔] memoryleakfix-1.0.0
  [✔] meteor-client-0.5.3-1820
  [✔] meteor-rejects-addon-0.2
  [✔] midnightcontrols-1.8.1+1.19.4
  [✔] mixintrace-1.1.1+1.17
  [✔] modelfix-1.10
  [✔] modmenu-6.1.0-rc.4
  [✔] mods
  [✔] morechathistory-1.1.1
  [✔] moreculling-1.19.4-0.17.0
  [✔] nochatreports-1.19.4-v2.1.1
  [✔] nofade-1.18-2.0.1
  [✔] notenoughcrashes-4.4.0+1.19.4-fabric
  [✔] open-parties-and-claims-fabric-1.19.4-0.17.3
  [✔] optigui-2.0.0-beta.3
  [✔] owo-lib-0.10.3+1.19.4
  [✔] physics-mod-pro-v151-fabric-1.19.4
  [✔] PresenceFootsteps-1.8.0
  [✔] puzzle-1.5.0+1.19.4
  [✔] reeses-sodium-options-1.5.0+mc1.19.4-build.72
  [✔] seedcrackerX-2.14.2
  [✔] smoothboot-fabric-1.19.4-1.7.0
  [✔] sodium-0.4.10+build.24
  [✔] sodium-extra-0.4.18+mc1.19.4-build.100
  [✔] sodium-fabric-mc1.19.4-0.4.10+build.24
  [✔] soundphysics-fabric-1.19.4-1.1.0
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] unsafe-world-random-access-detector-1.1.0
  [✔] vector-addon-0.3.8
  [✔] viafabricplus-2.6.6
  [✔] visuality-0.7.0
  [✔] vivecraft-1.19.4-0.0.15
  [✔] vmp-fabric-mc1.19.4-0.2.0+beta.7.71-all
  [✔] Xaeros_Minimap_23.4.0_Fabric_1.19.4
  [✔] XaerosWorldMap_1.30.0_Fabric_1.19.4
  [✔] yet-another-config-lib-fabric-2.5.0+1.19.4
  [✔] yosbr-0.1.1
  [✔] Zoomify-2.9.4

### Bug Description

[21:05:56] [Render thread/INFO]: Connecting to mineplex.eu, 25565
[21:05:56] [Server Connector #14/WARN]: Failed to fetch the key pair

### Steps to Reproduce

1. Joining server mineplex.eu with 1.19.4 emulating 1.19.2
2. Kicked with message: `multiplayer.disconnect.missing_public_key`

### Expected Behavior

joining game...

**Comment by FlorianMichael** [comment]
You have NoChatReports installed, the mod breaks chat signing as far as I know, please uninstall NoChatReports first and test it again, if it doesn't work, remove all mods.

**Comment by FlorianMichael** [comment]
You also have Krypton installed, so unless you built this version yourself from git, uninstall it too, because the current release version of Krypton is also not compact.

**Comment by Bluscream** [comment]
Disabling NCR and Krypton worked, but it's not really desirable having to cope with mojangs stupid punishment system for things that they shouldn't have control over. Why is this even clashing with VFP? It wasn't with normal VF or milticonnect

**Comment by FlorianMichael** [comment]
I don't think you understand what NoChatReports does, NoChatReports removes the secure profile system, you can't join secure profiles with it because it doesn't send the keys anymore, you can't expect my mod to work with it, NoChatReports breaks Minecraft so to speak.

**Comment by Bluscream** [comment]
And another semi-related question; what happens if you're trying to connect to a server with the same version as your client? Does VFP still do translations and stuff, or does it leave networking as is if server and client versions match?

**Comment by FlorianMichael** [comment]
If you select the native version, ViaFabricPlus does not modify anything in the pipeline, ViaVersion is then automatically deactivated.

**Comment by Bluscream** [comment]
> Disabling NCR and Krypton worked, but it's not really desirable having to cope with mojangs stupid punishment system for things that they shouldn't have control over. Why is this even clashing with VFP? It wasn't with normal VF or milticonnect

Why does it work fine on it's own then even on "secure" servers or even with multiconnect/VF. From what i've read/heard/seen it just rejects message signing when you're prompted (i.e. when you're sending your first message per session)

**Comment by FlorianMichael** [comment]
MultiConnect and ViaFabric do not change the remapping of the profile keys, Secure Chat was simply not implemented on 1.19.2.

**Comment by Bluscream** [comment]
Ahhh, now i get it. So essentially NCR is trying to exchange keys with the server and the server is like "what keys? i don't anything about keys, gtfo"

**Comment by FlorianMichael** [comment]
Minecraft has changed the way chat messages are encrypted, and in 1.19.0 a different key was used, ViaFabricPlus just builds in these changes, which ViaFabric or MultiConnect didn't do, can you join the same server with NoChatReports for 1.19.2 and see if that works?

**Comment by Bluscream** [comment]
This is without VFP but with 1.19.2 NCR: https://i.imgur.com/HOrIbYA.png
Cannot test with VFP because VFP doesn't exist for 1.19.2

**Comment by FlorianMichael** [comment]
I don't know, I just find NoChatReports kind of weird, and I can't really see a bug in my code to be honest, I just think NoChatReports is breaking something because I'm sticking to the Minecraft codebase, you can report it to NoChatReports.

**Comment by FlorianMichael** [comment]
You can also simply join mineplex with 1.19.3.

**Comment by FlorianMichael** [comment]
I just saw that when you connect to the server, the console says "Failed to fetch the key pair", VIaFabricPlus sends this message when Minecraft returns the fetchKeypair call null, so it's definitely a NoChatReports issue because it sets the keypair to null.

**Comment by Bluscream** [comment]
Here's a full log btw; https://mclo.gs/0KSMRUC#L1773

The first thing i can find about keypair stuff in their source is https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.4-Unified/src/main/java/com/aizistral/nochatreports/common/core/ServerSafetyState.java#L50

**Comment by FlorianMichael** [comment]
https://github.com/Aizistral-Studios/No-Chat-Reports/blob/3466c48dcb07d66f9c5a713975504aa8ce24a400/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinMinecraft.java#L30 This is the problem, if the SererSafetyState isn't on "Allow Chat signing" it just returns an empty profile Key Manager which contains an fetchKeypair Method which returns null

**Comment by FlorianMichael** [comment]
NoChatReports simply sets internal states to null, and ViaFabricPlus then assumes that there is no profile keypair and disables all remapps, which is what it is supposed to do.

**Comment by Bluscream** [comment]
Interesting stuff, i'm going to set my servers to not enforce secure stuff now, and i might bring this up in NCR's repo later
