### ISSUE TITLE
Incompatibility with Krypton

### ISSUE THREAD

**Issue by StckOverflw** [FlorianMichael/ViaFabricPlus#80]
### General Information

The mod has incompatibilities with [Krypton](https://modrinth.com/mod/krypton)

List of all mods I have installed:
- Cloth Config (v10.0.96)
- Dynamic FPS (v2.2.0)
- Gamma Utils (v1.6.14)
- Indium (v1.0.15)
- Iris (v1.6.0)
- Krypton (v0.2.2)
- Lithium (v0.11.1)
- Mod Menu (v6.1.0)
- OK Zoomer (v5.0.0-beta.11+1.19.4)
- Quilted Fabric API (v6.0.0-beta.3+0.76.0-1.9.4)
- Reese's Sodium Options (v1.5.0)
- Sodium (v0.4.10)
- Starlight (v1.1.1)
- ViaFabricPlus (v2.6.8)

When I disabled Krypton, it worked.

I'd understand if this is going to be a wontfix, but might be useful to put into the readme

### Bug Description

When switching the version to anything but the actual version of the client, the connection to the minecraft server fails

### Steps to Reproduce

1. Install ViaFabricPlus & Krypton
2. Switch from 1.19.4 to for example 1.19.1-1.19.2 
3. Try joining a server that is 1.19.2 only

### Expected Behavior

You should be able to join the server

**Comment by FlorianMichael** [comment]
In the latest git version of Krypton this is fixed, you have to build it yourself, or make an issue with Krypton that they make a new release.

**Comment by StckOverflw** [comment]
oh, thank you, didn't know that!
