### ISSUE TITLE
Excpetion on connecting to a server on quilt.

### ISSUE THREAD

**Issue by MarkusTieger** [FlorianMichael/ViaFabricPlus#81]
### General Information

I use quilt 0.18.10 with Minecraft 1.19.4 using temurin-17 jdk and quiltet fabric api "6.0.0-beta6+0.79.0-1.19.4".

On Fabric it is working on Quilt it's not.

The Exception:
`[17:55:40] [Render thread/INFO]: Connecting to mc.hypixel.net, 25565
[17:55:40] [Server Connector #2/ERROR]: Couldn't connect to server
java.lang.ClassCastException: class io.netty.channel.epoll.EpollEventLoopGroup cannot be cast to class io.netty.channel.EventLoopGroup (io.netty.channel.epoll.EpollEventLoopGroup is in unnamed module of loader 'app'; io.netty.channel.EventLoopGroup is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @457e2f02)
	at net.minecraft.class_2535.method_10753(class_2535.java:314) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_412$1.run(class_412.java:78) ~[transformed-mod-minecraft.i0:0/:?]`

I checked the javadoc: the EpollEventLoopGroup class extends from the MultithreadedEventLoopGroup class which implements the EventLoopGroup interface. I do not understand in any case, how the error has come about

### Bug Description

When i try to join a Minecraft server with this mod (and without modifying any settings) i get this exception:
`[17:55:40] [Render thread/INFO]: Connecting to mc.hypixel.net, 25565
[17:55:40] [Server Connector #2/ERROR]: Couldn't connect to server
java.lang.ClassCastException: class io.netty.channel.epoll.EpollEventLoopGroup cannot be cast to class io.netty.channel.EventLoopGroup (io.netty.channel.epoll.EpollEventLoopGroup is in unnamed module of loader 'app'; io.netty.channel.EventLoopGroup is in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @457e2f02)
	at net.minecraft.class_2535.method_10753(class_2535.java:314) ~[transformed-mod-minecraft.i0:0/:?]
	at net.minecraft.class_412$1.run(class_412.java:78) ~[transformed-mod-minecraft.i0:0/:?]`

### Steps to Reproduce

1. Installing Quilt with Quiltet Fabric API
2. Launch the Game
3. Joining a server for example "mc.hypixel.net" without modifying anything (like the current version)
4. You get kicked with this exception

### Expected Behavior

the game should not crash when i try to connect to a server

**Comment by FlorianMichael** [comment]
Hey, the error is already known, but it is not due to ViaFabricPlus but to the Quilt Loader, here is the Quilt Issue
https://github.com/QuiltMC/quilt-loader/issues/293

**Comment by Blayung** [comment]
Shouldn't this issue be closed then?

**Comment by FlorianMichael** [comment]
I will wait until Quilt fixes it

**Comment by TheGlitch76** [comment]
I can't reproduce this issue on Quilt Loader `0.18.10` with Fabric API or Quilted Fabric API on NixOS.

**Comment by FlorianMichael** [comment]
This is already fixed
