### ISSUE TITLE
Stuck in the air while respawning

### ISSUE THREAD

**Issue by Calvineries** [FlorianMichael/ViaFabricPlus#83]
### General Information

ViaFabricPlus, OptiFabric, Fabric-API

### Bug Description

When you die in certain game modes on this server and you use ViaFabric, you get stuck.

Console spam "Invalid entity data item type for field 8 on entity class_1295" until you return to the hub.

Here is full logs from my die to return to lobby : https://pastebin.com/raw/HXe9SGCF

### Steps to Reproduce

(i'm in 1.19.4, funcraft is in 1.9.4-1.11.2)

1. Join server "funcraft.net"
2. Join gamemode "Hikabrain" 1v1
3. When the game has started, die (by jumping in void or getting killed).
4. You are now stuck, you can't move.

### Expected Behavior

I should be able to move after respawn.

**Comment by FlorianMichael** [comment]
With which version are you connecting to funcraft?

**Comment by Calvineries** [comment]
@FlorianMichael I tried in 1.9.4 and 1.11.2.
The issue occurs in both cases.

**Comment by FlorianMichael** [comment]
Does this also happen with normal ViaFabric? If so, please report this to ViaVersion

**Comment by Calvineries** [comment]
Yes, that also happens with ViaFabric.

How am I supposed to report them? They ask to do a /viaversion dump, but that's something I'm not able to reproduce on a local server, it's a problem that only happens on Funcraft.
(and Funcraft don't use viaversion)

**Comment by FlorianMichael** [comment]
ViaFabric adds a /viafabricclient command, you can use this

**Comment by Calvineries** [comment]
OP permission level 3 is required for "/viafabricclient"
![image](https://user-images.githubusercontent.com/29179001/235789275-e639efde-a6da-480f-9beb-7b6bc6799208.png)

**Comment by FlorianMichael** [comment]
You can just call it on a different server where you have permissions

**Comment by FlorianMichael** [comment]
I will close this issue since it's not related to VFP
