### ISSUE TITLE
Unable to join 1.19.2 paper server

### ISSUE THREAD

**Issue by howtoleavetown** [FlorianMichael/ViaFabricPlus#84]
### General Information

Fabric API, FerriteCore, kennytv's epic force close loading screen mod for fabric, Krypton, Lithium, Mod Menu, Sodium, Starlight, ViaFabricPlus

### Bug Description

Joining constantiam.net (1.19.2 paper server) causes an error using the latest version (1.19.4)

`Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/37 (class_2673) was larger than I expected, found 27128 bytes extra whilst reading packet 37`

### Steps to Reproduce

Example:
1. Join constantiam.net set to 1.19.1-1.19.2 compatibility
2. See error

### Expected Behavior

Game should let me connect

**Comment by FlorianMichael** [comment]
In the latest git version of Krypton this is fixed, you have to build it yourself, or make an issue with Krypton that they make a new release.
