### ISSUE TITLE
unable to enter or create  a world with this mod

### ISSUE THREAD

**Issue by tlwsy** [FlorianMichael/ViaFabricPlus#86]
### General Information

AdvancedChatCore-1.19.4-1.5.10.jar
AdvancedChatFilters-1.19.4-1.2.8.jar
AdvancedChatHUD-1.19.4-1.3.8.jar
animatica-0.5+1.19.jar
architectury-8.1.79-fabric.jar
balm-fabric-1.19.4-6.0.2.jar
capes-1.5.2+1.19.3-fabric.jar
carpet-tis-addition-mc1.19.4-v1.46.1.jar
CITResewn-1.1.3+1.19.4.jar
clientcommands-2.7.11.jar
cloth-config-10.0.96-fabric.jar
continuity-3.0.0-beta.2+1.19.3.jar
Debugify-1.19.4+2.2.jar
entity_texture_features_fabric_1.19.4-4.4.0.jar
essential-client-1.19.4-1.3.4.jar
Essential-fabric_1-19.jar
EssentialGUI-1.8.8+1.19.4.jar
fabric-api-0.79.0+1.19.4.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
fabricskyboxes-0.6.5+mc1.19.4.jar
ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric.jar
iris-mc1.19.4-1.6.2.jar
ItemBorders-1.19.4-fabric-1.2.0.jar
libIPN-fabric-1.19.4-2.0.7.jar
LIST.TXT
malilib-fabric-1.19.4-0.15.3.jar
MasaGadget-3.1.289+1ca4352-stable.jar
oh-my-minecraft-client-0.5.jar
Prism-1.19.3-fabric-1.0.4.jar
rer-2.8.0.jar
showdurability-1.1.0+1.19.4.jar
tweakermore-mc1.19.4-v3.11.0.jar
tweakeroo-fabric-1.19.4-0.16.0.jar
viafabricplus-2.6.8.jar.disabled
WorldEditCUI-1.19.4+01.jar
yet-another-config-lib-forge-2.5.0+1.19.4.jar
[3D皮肤层] 3dskinlayers-fabric-1.5.3-mc1.19.4.jar
[Carpet - Fabric 版 Carpet（更早版本的Carpet Mod 在作者的 GitHub 主页上）] fabric-carpet-1.19.4-1.4.101+v230319.jar
[Gugle的Carpet附加包] gugle-carpet-addition-2.6.0-1.19.4.jar
[Lambda的动态光源] lambdynamiclights-2.3.0+1.19.4.jar
[REI工作方块] RoughlyEnoughProfessions-fabric-1.19.4-1.2.1.jar
[REI物品管理器] RoughlyEnoughItems-11.0.597.jar
[一键背包整理Next] InventoryProfilesNext-fabric-1.19.4-1.9.7.jar
[万用皮肤补丁] CustomSkinLoader_Fabric-14.16.jar
[冰山] Iceberg-1.19.4-fabric-1.1.8.jar
[创世神] worldedit-mod-7.2.14.jar
[动态FPS] dynamic-fps-2.2.0.jar
[合成辅助] craftingtweaks-fabric-1.19.4-17.0.2.jar
[实体模型特性] entity_model_features_fabric_1.19.4-0.2.8.jar
[实体渲染机制优化] entityculling-fabric-1.6.2-mc1.19.4.jar
[平滑转移] smoothswapping-0.9.jar
[手持物品信息] held-item-info-1.4.2.jar
[投影] litematica-fabric-1.19.4-0.14.3.jar
[旅行地图] journeymap-1.19.4-5.9.5-fabric.jar
[星光] starlight-1.1.1+fabric.ae22326.jar
[更多动画] notenoughanimations-fabric-1.6.3-mc1.19.4.jar
[更好的F3] BetterF3-6.0.1-Fabric-1.19.4.jar
[更好的进度] BetterAdvancements-Fabric-1.19.4-0.3.1.156.jar
[更好的钠视频设置按钮] bsvsb-3.0.3.jar
[更高级联机设置] mcwifipnp-1.6.4-1.19.4-fabric.jar
[极简血量显示] Neat-1.19.4-34-FABRIC.jar
[模组菜单] modmenu-6.2.2.jar
[物品滚轮] itemscroller-fabric-1.19.4-0.19.2.jar
[玉 ??] Jade-1.19.4-fabric-10.1.0.jar
[禁用聊天举报] NoChatReports-FABRIC-1.19.4-v2.1.1.jar
[细节盔甲] DetailArmorBar-2.6.3+1.19.4-fabric.jar
[聊天头像] chat_heads-0.10.12-fabric-1.19.4.jar
[自动汉化更新] I18nUpdateMod-3.4.2-all.jar
[输入法冲突修复] imblockerfabric-1.0.20_pre5.jar
[迷你HUD] minihud-fabric-1.19.4-0.26.2.jar
[钠 ・ 土径阴影] sodium-shadowy-path-blocks-3.1.0.jar
[钠 ・ 扩展] sodium-extra-0.4.19+mc1.19.3-build.101.jar
[钠] sodium-fabric-mc1.19.4-0.4.11+build.26.jar
[铁氧体磁芯] ferritecore-5.2.0-fabric.jar
[铟] indium-1.0.17+mc1.19.4.jar
[锂] lithium-fabric-mc1.19.4-0.11.1.jar
[键位冲突显示] Controlling-fabric-1.19.4-11.0.0.2.jar
[魔法类库] magiclib-0.7.293+17aa28c-stable.jar

### Bug Description

When I installed this mod,i could not enter or create a world.

### Steps to Reproduce

1. Installed the mods.
2. Create a new world.
3. When the progress bar is 100%,game stuck

https://drive.google.com/file/d/1l8VFQWjpJX8FjQc_zD9NfoNW-6w5Hq-r/view?usp=sharing
you can get these mods from this link

### Expected Behavior

the game should completed the process

**Comment by cxzlw** [comment]
hey, it seems that ItemScroller and ViaFabricPlus are incompactiable. Maybe disabling ItemScroller will work. 
看起来ItemScroller和ViaFabricPlus并不兼容，禁用可以解决问题

**Comment by FlorianMichael** [comment]
Does this issue also happen with only ViaFabricPlus? + Can you please send your latest.log file or an error

**Comment by cxzlw** [comment]
This issue does not happen with only ViaFabricPlus. Only using both ItemScroller and ViaFabricPlus will cause the issue. I will send a log here. Thank you.

**Comment by cxzlw** [comment]
The game stuck on Joining World page and I am finally kicked by Authme plugin because login timeout.

**Comment by FlorianMichael** [comment]
I need a log file

**Comment by cxzlw** [comment]
> I need a log file

Yes. I have one. But it's too large and I am trying to upload it to some websites. Can you suggest any website to upload large log?

**Comment by cxzlw** [comment]
[The log](https://1drv.ms/u/s!AnM9HlY-IOtPhQRdCUKSuE_k2Jpk?e=gUQiHu)

**Comment by FlorianMichael** [comment]
Can you join the discord that I can send you a test build for you to try?

**Comment by cxzlw** [comment]
> Can you join the discord that I can send you a test build for you to try?

I'd love to join and try the test build. However I am on my bed and is going to sleep now. How about tomorrow? 
BTW: I am not allow to send messages in the Discord server because of the sms verification and I cannot receive Discord's sms message. (Maybe I cannot receive foreign sms messages? I am in China and recently I cannot receive sms messages from Steam too. )

**Comment by FlorianMichael** [comment]
Alright, I verified you know, now you can write messages
