### ISSUE TITLE
ViaBedrock Updated to 1.19.80!!!

### ISSUE THREAD

**Issue by pierrelasse** [FlorianMichael/ViaFabricPlus#87]
https://github.com/RaphiMC/ViaBedrock/commit/8a1d05500e28d86f0af12478fcd3010d1b2213ad

Alarm es kommt ein Notruf an.
Feuerwehrmann Sam ist unser Mann.

Also how to select labels?

**Comment by pierrelasse** [comment]
![grafik](https://user-images.githubusercontent.com/76223390/236616277-8a1a5cee-6f18-48c7-9a05-753d24755869.png)
![grafik](https://user-images.githubusercontent.com/76223390/236616301-8226c505-62ed-43fd-b9e4-e4965a6bd4e8.png)

**Comment by FlorianMichael** [comment]
I won't create a new release for this, just download it from the Actions and stop spamming with troll issues

**Comment by pierrelasse** [comment]
Okay

**Comment by pierrelasse** [comment]
I just wanted to notify you about but ok

**Comment by FlorianMichael** [comment]
I already know this, VB is automatically updated because it has no version system yet
Und hör mit dem Trollen auf

**Comment by pierrelasse** [comment]
Ich trolle nicht -_-

**Comment by pierrelasse** [comment]
Zumindestens wollte ich das nicht

**Comment by pierrelasse** [comment]
Ich finde das hier ein cooles Projekt und wollte helfen

**Comment by FlorianMichael** [comment]
Done with the v2.7.0 version
