### ISSUE TITLE
Can't connect to any servers 1.6.4 and before

### ISSUE THREAD

**Issue by thatonespookymonth** [FlorianMichael/ViaFabricPlus#89]
on viafabricplus 2.70 1.19.4 i am unable to connect to any version up to and including 1.6.4. my modlist is as follows 

> 3dskinlayers-fabric-1.5.3-mc1.19.4.jar
appleskin-fabric-mc1.19.4-2.4.3.jar
betterbiomeblend-1.19.0-1.3.6-fabric.jar
c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar
DistantHorizons-1.6.11a-1.19.4.jar
exordium-fabric-1.0.3-mc1.19.4.jar
fabric-api-0.80.0+1.19.4.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
ferritecore-5.2.0-fabric.jar
ImmediatelyFast-1.1.12+1.19.4.jar
indium-1.0.17+mc1.19.4.jar
iris-mc1.19.4-1.6.2 (1).jar
Jade-1.19.4-fabric-10.1.0.jar
lambdynamiclights-2.3.0+1.19.4.jar
lazydfu-0.1.3.jar
litematica-fabric-1.19.4-0.14.3.jar
litematica-printer-1.19.3-3.1.jar
lithium-fabric-mc1.19.4-0.11.1.jar
malilib-fabric-1.19.4-0.15.3.jar
memoryleakfix-fabric-1.17+-1.0.0.jar
midnightlib-fabric-1.1.0.jar
modmenu-6.2.2.jar
moreculling-1.19.4-0.17.0.jar
puzzle-1.5.0+1.19.4.jar
reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
sodium-extra-0.4.19+mc1.19.3-build.101.jar
sodium-fabric-mc1.19.4-0.4.11+build.26 (1).jar
starlight-1.1.1+fabric.ae22326.jar
viafabricplus-2.7.0.jar
yet-another-config-lib-fabric-2.5.0+1.19.4.jar
Zoomify-2.9.4.jar

**Comment by FlorianMichael** [comment]
Can you please provide a log and a crash message / kick message?
