### ISSUE TITLE
Suggestion: Method to override version per server

### ISSUE THREAD

**Issue by RuiNtD** [FlorianMichael/ViaFabricPlus#9]
There should be a way to override the Minecraft version on a per-server basis, [similar to ViaFabric](https://github.com/ViaVersion/ViaFabric#how-can-i-set-the-version-for-specific-servers).

**Comment by FlorianMichael** [comment]
done, https://github.com/FlorianMichael/ViaFabricPlus/releases/tag/v2.3.1
